### ISSUE TITLE
upgrade dependencies to support stylelint v14

### ISSUE THREAD

**Issue by bingtsingw** [culur/config-stylelint-v1#310]
Some of the dependent configs do not support v14 of `stylelint`, such as `function-calc-no-invalid` rule, I test upgrade dependencies locally, and it works.

Could you please update the dependencies to truly support v14, thank you very much

**Comment by phamhongphuc** [comment]
Looks like the `function-calc-no-invalid` rule was removed in v14.
Let me check and update the dependencies.

**Comment by bingtsingw** [comment]
> Looks like the `function-calc-no-invalid` rule was removed in v14. Let me check and update the dependencies.

Yes, it seems some of the dependencies has the `function-calc-no-invalid` rule, which breaks with v14, when I upgrade all dependencies and rebuild, the error message disappears.
