### ISSUE TITLE
support jsx out of the box

### ISSUE THREAD

**Issue by bingtsingw** [culur/config-stylelint-v1#317]
On v13, I don't need to do anything to support `jsx`, but now, I need to config `overrides` to support `jsx`, can it be supported out of the box?

This is my `.stylelintrc.json` file, I'm not sure if it's perfect
```
{
  "extends": ["@culur/stylelint-config"],
  "overrides": [
    {
      "files": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
      "customSyntax": "postcss-jsx"
    }
  ]
}
```

**Comment by phamhongphuc** [comment]
I hardly use the CSS in JS syntax in my projects, so it would be quite difficult to test and maintain this feature.

On the other hand, the package [`postcss-jsx`](https://github.com/gucong3000/postcss-jsx) [has not been maintained from 2020](https://github.com/gucong3000/postcss-jsx/issues/66) and has been forked into [stylelint/postcss-css-in-js](https://github.com/stylelint/postcss-css-in-js)

And then, `postcss-css-in-js` is [deprecated](https://github.com/stylelint/postcss-css-in-js/issues/225) again.

So the config can't support `CSS in JS` out of the box.
